### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getAttribute' of null

### ISSUE THREAD

**Issue by riomhaire** [frairon/go-outline#43] opened 2016-06-28 17:16 UTC
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 15.04
**Thrown From**: [go-outline](https://github.com/frairon/go-outline) package, v0.4.0
### Stack Trace

Uncaught TypeError: Cannot read property 'getAttribute' of null

```
At /home/gremlin/.atom/packages/go-outline/node_modules/d3/node_modules/d3-selection/build/d3-selection.js:590

TypeError: Cannot read property 'getAttribute' of null
    at Selection.selection_attr [as attr] (/home/gremlin/.atom/packages/go-outline/node_modules/d3/node_modules/d3-selection/build/d3-selection.js:590:17)
    at createChildren (/home/gremlin/.atom/packages/go-outline/lib/go-outline-view.coffee:386:49)
    at /home/gremlin/.atom/packages/go-outline/lib/go-outline-view.coffee:417:38
    at Selection.selection_call [as call] (/home/gremlin/.atom/packages/go-outline/node_modules/d3/node_modules/d3-selection/build/d3-selection.js:500:14)
    at GoOutlineView.module.exports.GoOutlineView.updateSymbolList (/home/gremlin/.atom/packages/go-outline/lib/go-outline-view.coffee:417:26)
    at GoOutlineView.updateSymbolList (/home/gremlin/.atom/packages/go-outline/lib/go-outline-view.coffee:1:1)
    at Object.subscribeTo.click [as __NONE__] (/home/gremlin/.atom/packages/go-outline/lib/go-outline-view.coffee:99:8)
    at HTMLDivElement.listener (/home/gremlin/.atom/packages/go-outline/node_modules/atom-utils/lib/mixins/events-delegation.js:108:41)
```
### Commands

```
     -0:27.9.0 go-outline:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "activate-power-mode",
      "go-playground"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-go, v1.1.0
builder-go, v1.0.0
go-config, v1.1.4
go-debug, v0.1.14
go-get, v1.0.3
go-outline, v0.4.0
go-plus, v4.1.0
go-quick-import, v0.2.1-rc.0
go-signature-statusbar, v1.1.0
godoc, v0.2.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
lint, v0.0.1
linter, v1.11.14
navigator-godef, v1.0.3
script-runner, v1.8.4
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by frairon** [comment] 2016-07-15 07:44
Hey riomhaire, 
thanks you took the time to report this. 
Unfortunately I cannot reproduce this, although I haven't tried  especially with Ubuntu 15.04. 
Can you trigger that error repeatedly? If so, could you give me the code that causes that behavior?
It would be really helpful.
Cheers!

**Comment by frairon** [comment] 2017-01-31 08:54
cannot reproduce, I'll close it.

**Closed as completed by frairon** 2017-01-31 08:54 UTC

**Comment by riomhaire** [comment] 2017-09-12 05:53
Thanks - will get onto that when I get back this evening
